import { normalizeRoute } from "./discover";
import { ProjectFile } from "./types";

export function routeFilePath(route: string): string {
  const r = normalizeRoute(route).replace(/^\/+/, "");
  return r ? `app/${r}/route.ts` : "app/route.ts";
}

export function routeHandler(html: string): string {
  return `// Auto-generated by Framer2NextJS.
// Served verbatim to preserve Framer's React Suspense comment hydration markers (<!--$-->).
// Preserving these markers ensures 100% hydration speed and prevents client re-render regressions.
export const dynamic = "force-static";

const HTML = ${JSON.stringify(html)};

export function GET() {
  return new Response(HTML, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=0, s-maxage=31536000, stale-while-revalidate=86400",
      "netlify-cdn-cache-control": "public, durable, max-age=31536000, stale-while-revalidate=86400",
    },
  });
}
`;
}

export function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "14.2.24",
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^18.3.1",
        "@types/react-dom": "^18.3.1",
        typescript: "^5",
      },
    },
    null,
    2
  );
}

export const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};
module.exports = nextConfig;
`;

export const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2021",
      lib: ["dom", "dom.iterable", "esnext"],
      module: "esnext",
      moduleResolution: "bundler",
      strict: true,
      skipLibCheck: true,
      noEmit: true,
      esModuleInterop: true,
      resolveJsonModule: true,
      isolatedModules: true,
      incremental: true,
      jsx: "preserve",
      plugins: [{ name: "next" }],
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2
);

export const GITIGNORE = `/node_modules
/.next/
/out/
.env*.local
next-env.d.ts
*.tsbuildinfo
.DS_Store
`;

export function vercelJson(): string {
  return JSON.stringify(
    {
      cleanUrls: true,
      trailingSlash: false,
      headers: [
        {
          source: "/(.*)\\.(webp|avif|png|jpg|jpeg|gif|svg|ico|woff2|woff|ttf|otf|mp4|webm|css|js)",
          headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
        },
        {
          source: "/(.*)",
          headers: [
            {
              key: "Cache-Control",
              value: "public, max-age=0, s-maxage=86400, stale-while-revalidate=604800",
            },
            { key: "X-Content-Type-Options", value: "nosniff" },
          ],
        },
      ],
    },
    null,
    2
  );
}

export function netlifyHeaders(): string {
  return [
    "/assets/*",
    "  Cache-Control: public, max-age=31536000, immutable",
    "/*.webp",
    "  Cache-Control: public, max-age=31536000, immutable",
    "/*.woff2",
    "  Cache-Control: public, max-age=31536000, immutable",
    "/*.css",
    "  Cache-Control: public, max-age=31536000, immutable",
    "/*.js",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
  ].join("\n");
}

export function readme(sourceUrl: string, pageCount: number): string {
  return `# Next.js Project (Converted from Framer)

Exported from **${sourceUrl}** using [Framer2NextJS](https://github.com).
Includes **${pageCount} page(s)** statically prerendered as Next.js App Router routes.

## Quick Start

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Run local development server
npm run dev
# Open http://localhost:3000

# 3. Production build
npm run build
npm start
\`\`\`

## Features & Optimizations Included

- **100% Animation & Interaction Parity**: Served through App Router static route handlers (\`app/<route>/route.ts\`) preserving React Suspense comment markers (\`<!--$-->\`) for instant client hydration.
- **Image Optimization**: Images are re-encoded to WebP and self-hosted under \`public/assets/img/\`.
- **Font Self-Hosting**: Web fonts downloaded locally to \`public/assets/fonts/\` with \`font-display: swap\` forced.
- **SEO & Accessibility**: Prioritized LCP hero image (\`fetchpriority="high"\`), added \`lang="en"\`, descriptive \`title\` tags for iframes, accessibility labels for icon links.
- **Badge & Tracker Stripping**: Removed "Made in Framer" badge and Framer telemetry trackers.
- **Zero Vendor Lock-in**: Deploy to **Vercel**, **Netlify**, or **Cloudflare Pages** in one click.
`;
}

export function getScaffoldFiles(hostName: string, sourceUrl: string, pageCount: number): ProjectFile[] {
  return [
    { path: "package.json", content: packageJson(`${hostName}-nextjs`) },
    { path: "next.config.js", content: NEXT_CONFIG },
    { path: "tsconfig.json", content: TSCONFIG },
    { path: ".gitignore", content: GITIGNORE },
    { path: "vercel.json", content: vercelJson() },
    { path: "_headers", content: netlifyHeaders() },
    { path: "README.md", content: readme(sourceUrl, pageCount) },
  ];
}
